# here we are installing the tomcat in the remote server and trying to copy a file to remote host.

- name : this play is installing the tomcat in the remote server
  hosts : all
  become : yes
  tasks :
    - name : installing the tomcat...
      yum :
        name : tomcat
        state : latest
    - name : downloading the zip file to the remote server
      ansible.builtin.unarchive :
        src: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
        dest : /tmp/
        remote_src: yes
    - name : download and install the jenkins
      yum :
        name : jenkins
        state : latest
      tags :
        - jenkins_server