# various types of variable declaration


# We are declaring the variable in each play
# The variable of one play cannot be used in another play (By default)

- name: This shows how we declare the play variable
  hosts: all
  vars :
    URL : play.example.com
  tasks :
    - name : print URL
      ansible.builtin.debug:
        msg : URL == {{ URL }}

# we are declaring the variable in task

- name : here we are declaring the variable in var file
  hosts : all
  vars_files : demo-var.yml
  tasks :
    - name : collecting variable from var file
      ansible.builtin.debug:
        msg : URL == {{ URL }}

# Here we are declaring the task level variables

- name : Task level variable are declaring here
  hosts : all
  tasks :
    - name : print the variable in task level
      ansible.builtin.debug :
        msg : URL == {{ URL }}

        ## declaring here as below
      vars :
        URL : task.example.com

# here we are declaring the variable in inventory file

- name : print the variable from inventory file
  hosts : all
  tasks :
    - name : print the URL
      ansible.builtin.debug :
        msg : URL == {{ URL }}


# here we are passing the variable from cli

- name : Here we are declaring the variables in inventory file which names as main.yml
  hosts : all
  tasks :
    - name : print the variable from CLI
      ansible.builtin.debug :
        msg : URL == {{ URL }}